######################################################################
# Automatically generated by qmake (2.01a) ?? 6. ??? 01:35:31 2019
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
SOURCES += main.cpp mainwindow.cpp
